name: Ember CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1
      with:
        node-version: 12
        yarn-version: 1.22.4
    - uses: mydea/actions-ember-testing@v2
    - name: Install dependencies
      run: yarn install
    - name: Lint JS
      run: yarn lint:js
    - name: Lint HBS
      run: yarn lint:hbs
    - name: Check Size
      run: yarn bundlesize
    - name: Run tests
      run: yarn test
      env:
        CI: true
